/* ═══════════════════════════════════════════════
   ATUM Sample Etymology Data
   ═══════════════════════════════════════════════ */

window.ATUM_DATA = {
  roots: {
    ATUM: {
      id: 'ATUM',
      arabic: 'أتم',
      transliteration: 'ʾa-t-m',
      meaning: 'Completion · Totality · Unity',
      principle: 'The electromagnetic field of unity — that which makes whole and indivisible',
      color: '#22C55E',
      colorDim: 'rgba(34, 197, 94, 0.15)',
      emoji: '🟢',
    },
    BULL: {
      id: 'BULL',
      arabic: 'بعل',
      transliteration: 'b-ʿ-l',
      meaning: 'Power · Lordship · Mastery',
      principle: 'The outward electromagnetic radiation — fire, authority, and creative force',
      color: '#EF4444',
      colorDim: 'rgba(239, 68, 68, 0.15)',
      emoji: '🔴',
    },
    TOR: {
      id: 'TOR',
      arabic: 'طور',
      transliteration: 'ṭ-w-r',
      meaning: 'Cycle · Phase · Turning',
      principle: 'Gravitational pull inward — water, structure, and recurring transformation',
      color: '#3B82F6',
      colorDim: 'rgba(59, 130, 246, 0.15)',
      emoji: '🔵',
    }
  },

  words: [
    // ── ATUM words ──
    {
      id: 'atom',
      european: 'atom',
      arabicRoot: 'أتم',
      rootId: 'ATUM',
      transliteration: 'ʾatam',
      meaning: 'indivisible completeness',
      rule: 'ʾ-t-m → a-t-o-m (vowel insertion, hamza drop)',
      confidence: 'proven',
      languages: ['English', 'Greek', 'Latin'],
      path: 'Arabic أتم → Greek ἄτομος → Latin atomus → English atom',
      abjad: 441,
    },
    {
      id: 'autumn',
      european: 'autumn',
      arabicRoot: 'أتم',
      rootId: 'ATUM',
      transliteration: 'ʾatam',
      meaning: 'completion of the annual cycle',
      rule: 'ʾ-t-m → au-t-u-mn (nasalization, vowel shift)',
      confidence: 'proven',
      languages: ['English', 'Latin', 'Etruscan'],
      path: 'Arabic أتم → Etruscan 𐌀𐌕𐌖𐌌 → Latin autumnus → English autumn',
      abjad: 441,
    },
    {
      id: 'ultimate',
      european: 'ultimate',
      arabicRoot: 'أتم',
      rootId: 'ATUM',
      transliteration: 'ʾatam',
      meaning: 'the final, the complete',
      rule: 'ʾ-t-m → ul-t-im-ate (prefix + vowel expansion)',
      confidence: 'strong',
      languages: ['English', 'Latin'],
      path: 'Arabic أتم → Latin ultimus → English ultimate',
      abjad: 441,
    },
    {
      id: 'anatomy',
      european: 'anatomy',
      arabicRoot: 'أتم',
      rootId: 'ATUM',
      transliteration: 'ʾatam',
      meaning: 'cutting to reveal completeness',
      rule: 'ʾ-t-m → ana-t-o-my (Greek prefix ana- + root)',
      confidence: 'moderate',
      languages: ['English', 'Greek'],
      path: 'Arabic أتم → Greek ἀνατομή → Latin anatomia → English anatomy',
      abjad: 441,
    },
    // ── BULL words ──
    {
      id: 'bull',
      european: 'bull',
      arabicRoot: 'بعل',
      rootId: 'BULL',
      transliteration: 'baʿl',
      meaning: 'lord of the herd, raw power',
      rule: 'b-ʿ-l → b-u-ll (ʿayn → vowel, lām gemination)',
      confidence: 'proven',
      languages: ['English', 'Old Norse', 'Proto-Germanic'],
      path: 'Arabic بعل → Proto-Semitic *baʿl → Proto-Germanic *bullô → English bull',
      abjad: 132,
    },
    {
      id: 'bold',
      european: 'bold',
      arabicRoot: 'بعل',
      rootId: 'BULL',
      transliteration: 'baʿl',
      meaning: 'having power, daring authority',
      rule: 'b-ʿ-l → b-o-ld (ʿayn → vowel, d-suffix)',
      confidence: 'strong',
      languages: ['English', 'Old English', 'Germanic'],
      path: 'Arabic بعل → Germanic *balþ- → Old English beald → English bold',
      abjad: 132,
    },
    {
      id: 'bell',
      european: 'bell',
      arabicRoot: 'بعل',
      rootId: 'BULL',
      transliteration: 'baʿl',
      meaning: 'announcement of authority',
      rule: 'b-ʿ-l → b-e-ll (ʿayn → vowel, lām gemination)',
      confidence: 'moderate',
      languages: ['English', 'Old English'],
      path: 'Arabic بعل → Old English belle → English bell',
      abjad: 132,
    },
    {
      id: 'baal',
      european: 'Baal',
      arabicRoot: 'بعل',
      rootId: 'BULL',
      transliteration: 'baʿl',
      meaning: 'lord, master, deity of power',
      rule: 'b-ʿ-l → B-a-a-l (direct transliteration)',
      confidence: 'proven',
      languages: ['English', 'Hebrew', 'Phoenician'],
      path: 'Arabic بعل → Phoenician 𐤁𐤏𐤋 → Hebrew בַּעַל → English Baal',
      abjad: 132,
    },
    // ── TOR words ──
    {
      id: 'tour',
      european: 'tour',
      arabicRoot: 'طور',
      rootId: 'TOR',
      transliteration: 'ṭūr',
      meaning: 'cyclical journey through phases',
      rule: 'ṭ-w-r → t-ou-r (ṭāʾ → t, wāw → ou)',
      confidence: 'proven',
      languages: ['English', 'French', 'Latin'],
      path: 'Arabic طور → Latin tornus → French tour → English tour',
      abjad: 279,
    },
    {
      id: 'tower',
      european: 'tower',
      arabicRoot: 'طور',
      rootId: 'TOR',
      transliteration: 'ṭūr',
      meaning: 'rising turn, mountain peak',
      rule: 'ṭ-w-r → t-ow-er (ṭāʾ → t, wāw → ow)',
      confidence: 'proven',
      languages: ['English', 'French', 'Latin', 'Greek'],
      path: 'Arabic طور → Greek τύρρις → Latin turris → French tour → English tower',
      abjad: 279,
    },
    {
      id: 'torus',
      european: 'torus',
      arabicRoot: 'طور',
      rootId: 'TOR',
      transliteration: 'ṭūr',
      meaning: 'the turning shape, ring of cycles',
      rule: 'ṭ-w-r → t-or-us (Latin suffix -us)',
      confidence: 'strong',
      languages: ['English', 'Latin'],
      path: 'Arabic طور → Latin torus → English torus',
      abjad: 279,
    },
    {
      id: 'tornado',
      european: 'tornado',
      arabicRoot: 'طور',
      rootId: 'TOR',
      transliteration: 'ṭūr',
      meaning: 'violent turning, spiral destruction',
      rule: 'ṭ-w-r → tor-nado (root + Spanish -nado)',
      confidence: 'moderate',
      languages: ['English', 'Spanish'],
      path: 'Arabic طور → Spanish tronada/tornado → English tornado',
      abjad: 279,
    },
  ],

  letters: [
    { letter: 'أ', name: 'Alif', transliteration: 'ʾ', phoenician: '𐤀', rootAssociation: 'ATUM', wordCount: 23 },
    { letter: 'ب', name: 'Bāʾ', transliteration: 'b', phoenician: '𐤁', rootAssociation: 'BULL', wordCount: 18 },
    { letter: 'ت', name: 'Tāʾ', transliteration: 't', phoenician: '𐤕', rootAssociation: 'TOR', wordCount: 15 },
    { letter: 'ط', name: 'Ṭāʾ', transliteration: 'ṭ', phoenician: '𐤈', rootAssociation: 'TOR', wordCount: 21 },
    { letter: 'ع', name: 'ʿAyn', transliteration: 'ʿ', phoenician: '𐤏', rootAssociation: 'BULL', wordCount: 27 },
    { letter: 'ل', name: 'Lām', transliteration: 'l', phoenician: '𐤋', rootAssociation: 'BULL', wordCount: 19 },
    { letter: 'م', name: 'Mīm', transliteration: 'm', phoenician: '𐤌', rootAssociation: 'ATUM', wordCount: 22 },
    { letter: 'و', name: 'Wāw', transliteration: 'w', phoenician: '𐤅', rootAssociation: 'TOR', wordCount: 16 },
    { letter: 'ر', name: 'Rāʾ', transliteration: 'r', phoenician: '𐤓', rootAssociation: 'TOR', wordCount: 14 },
  ],

  stats: {
    totalWords: 5083,
    provenWords: 96,
    sources: 5,
    cnnAccuracy: 99.7,
    pValue: 0.0001,
    correlation: -0.693,
  },

  confidenceLevels: {
    proven:   { icon: '🔬', label: 'Proven',   description: 'Statistically confirmed by CNN analysis' },
    strong:   { icon: '🧩', label: 'Strong',   description: 'Multiple corroborating patterns found' },
    moderate: { icon: '🔍', label: 'Moderate', description: 'Clear pattern with some uncertainty' },
    emerging: { icon: '❓', label: 'Emerging', description: 'Initial observation, needs more data' },
  },

  wordOfDay: {
    european: 'tornado',
    arabicRoot: 'طور',
    rootId: 'TOR',
    transliteration: 'ṭūr',
    insight: 'The violent turning of a tornado mirrors the Arabic root ṭ-w-r (طور), meaning "cycle" and "phase" — the same root that gives us tour, tower, and torus.',
  },
};
